# coding: utf-8

"""
    CWMS Data API

    CWMS REST API for Data Retrieval  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import cda_client
from cda_client.api.locations_api import LocationsApi  # noqa: E501
from cda_client.rest import ApiException


class TestLocationsApi(unittest.TestCase):
    """LocationsApi unit test stubs"""

    def setUp(self):
        self.api = LocationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_cwms_data_locations_with_location_id(self):
        """Test case for delete_cwms_data_locations_with_location_id

        Delete cwmsData locations with locationId  # noqa: E501
        """
        pass

    def test_get_cwms_data_locations(self):
        """Test case for get_cwms_data_locations

        Get cwmsData locations  # noqa: E501
        """
        pass

    def test_get_cwms_data_locations_with_location_id(self):
        """Test case for get_cwms_data_locations_with_location_id

        Get cwmsData locations with locationId  # noqa: E501
        """
        pass

    def test_patch_cwms_data_locations_with_location_id(self):
        """Test case for patch_cwms_data_locations_with_location_id

        Patch cwmsData locations with locationId  # noqa: E501
        """
        pass

    def test_post_cwms_data_locations(self):
        """Test case for post_cwms_data_locations

        Post cwmsData locations  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
