# coding: utf-8

"""
    CWMS Data API

    CWMS REST API for Data Retrieval  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import cda_client
from cda_client.models.csv_v1_location_group import CsvV1LocationGroup  # noqa: E501
from cda_client.rest import ApiException


class TestCsvV1LocationGroup(unittest.TestCase):
    """CsvV1LocationGroup unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCsvV1LocationGroup(self):
        """Test CsvV1LocationGroup"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cda_client.models.csv_v1_location_group.CsvV1LocationGroup()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
