# coding: utf-8

"""
    CWMS Data API

    CWMS REST API for Data Retrieval  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import cda_client
from cda_client.models.blob import Blob  # noqa: E501
from cda_client.rest import ApiException


class TestBlob(unittest.TestCase):
    """Blob unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBlob(self):
        """Test Blob"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cda_client.models.blob.Blob()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
