# coding: utf-8

"""
    CWMS Data API

    CWMS REST API for Data Retrieval  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import cda_client
from cda_client.api.time_series_categories_api import TimeSeriesCategoriesApi  # noqa: E501
from cda_client.rest import ApiException


class TestTimeSeriesCategoriesApi(unittest.TestCase):
    """TimeSeriesCategoriesApi unit test stubs"""

    def setUp(self):
        self.api = TimeSeriesCategoriesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_cwms_data_timeseries_category_with_category_id(self):
        """Test case for delete_cwms_data_timeseries_category_with_category_id

        Delete cwmsData timeseries category with categoryId  # noqa: E501
        """
        pass

    def test_get_cwms_data_timeseries_category(self):
        """Test case for get_cwms_data_timeseries_category

        Get cwmsData timeseries category  # noqa: E501
        """
        pass

    def test_get_cwms_data_timeseries_category_with_category_id(self):
        """Test case for get_cwms_data_timeseries_category_with_category_id

        Get cwmsData timeseries category with categoryId  # noqa: E501
        """
        pass

    def test_post_cwms_data_timeseries_category(self):
        """Test case for post_cwms_data_timeseries_category

        Post cwmsData timeseries category  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
