# coding: utf-8

"""
    CWMS Data API

    CWMS REST API for Data Retrieval  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import cda_client
from cda_client.api.clob_api import ClobApi  # noqa: E501
from cda_client.rest import ApiException


class TestClobApi(unittest.TestCase):
    """ClobApi unit test stubs"""

    def setUp(self):
        self.api = ClobApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_cwms_data_clobs_with_clob_id(self):
        """Test case for delete_cwms_data_clobs_with_clob_id

        Delete cwmsData clobs with clobId  # noqa: E501
        """
        pass

    def test_get_cwms_data_clobs(self):
        """Test case for get_cwms_data_clobs

        Get cwmsData clobs  # noqa: E501
        """
        pass

    def test_get_cwms_data_clobs_with_clob_id(self):
        """Test case for get_cwms_data_clobs_with_clob_id

        Get cwmsData clobs with clobId  # noqa: E501
        """
        pass

    def test_patch_cwms_data_clobs_with_clob_id(self):
        """Test case for patch_cwms_data_clobs_with_clob_id

        Patch cwmsData clobs with clobId  # noqa: E501
        """
        pass

    def test_post_cwms_data_clobs(self):
        """Test case for post_cwms_data_clobs

        Post cwmsData clobs  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
