# coding: utf-8

"""
    CWMS Data API

    CWMS REST API for Data Retrieval  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import cda_client
from cda_client.api.default_api import DefaultApi  # noqa: E501
from cda_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_cwms_data(self):
        """Test case for get_cwms_data

        Get cwmsData  # noqa: E501
        """
        pass

    def test_get_cwms_data_levels_with_level_id_timeseries(self):
        """Test case for get_cwms_data_levels_with_level_id_timeseries

        Get cwmsData levels with levelId timeseries  # noqa: E501
        """
        pass

    def test_get_cwms_data_timeseries_recent_with_group_id(self):
        """Test case for get_cwms_data_timeseries_recent_with_group_id

        Get cwmsData timeseries recent with groupId  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
