# coding: utf-8

"""
    CWMS Data API

    CWMS REST API for Data Retrieval  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import cda_client
from cda_client.api.units_api import UnitsApi  # noqa: E501
from cda_client.rest import ApiException


class TestUnitsApi(unittest.TestCase):
    """UnitsApi unit test stubs"""

    def setUp(self):
        self.api = UnitsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_cwms_data_units(self):
        """Test case for get_cwms_data_units

        Get cwmsData units  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
