# coding: utf-8

"""
    CWMS Data API

    CWMS REST API for Data Retrieval  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import cda_client
from cda_client.models.offices_fmt import OfficesFMT  # noqa: E501
from cda_client.rest import ApiException


class TestOfficesFMT(unittest.TestCase):
    """OfficesFMT unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOfficesFMT(self):
        """Test OfficesFMT"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cda_client.models.offices_fmt.OfficesFMT()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
