# coding: utf-8

"""
    CWMS Data API

    CWMS REST API for Data Retrieval  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import cda_client
from cda_client.api.time_series_api import TimeSeriesApi  # noqa: E501
from cda_client.rest import ApiException


class TestTimeSeriesApi(unittest.TestCase):
    """TimeSeriesApi unit test stubs"""

    def setUp(self):
        self.api = TimeSeriesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_cwms_data_timeseries_with_timeseries(self):
        """Test case for delete_cwms_data_timeseries_with_timeseries

        Delete cwmsData timeseries with timeseries  # noqa: E501
        """
        pass

    def test_get_cwms_data_timeseries(self):
        """Test case for get_cwms_data_timeseries

        Get cwmsData timeseries  # noqa: E501
        """
        pass

    def test_patch_cwms_data_timeseries_with_timeseries(self):
        """Test case for patch_cwms_data_timeseries_with_timeseries

        Patch cwmsData timeseries with timeseries  # noqa: E501
        """
        pass

    def test_post_cwms_data_timeseries(self):
        """Test case for post_cwms_data_timeseries

        Post cwmsData timeseries  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
