# coding: utf-8

"""
    CWMS Data API

    CWMS REST API for Data Retrieval  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import cda_client
from cda_client.models.rating_metadata_list import RatingMetadataList  # noqa: E501
from cda_client.rest import ApiException


class TestRatingMetadataList(unittest.TestCase):
    """RatingMetadataList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRatingMetadataList(self):
        """Test RatingMetadataList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cda_client.models.rating_metadata_list.RatingMetadataList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
