# coding: utf-8

"""
    CWMS Data API

    CWMS REST API for Data Retrieval  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import cda_client
from cda_client.api.catalog_api import CatalogApi  # noqa: E501
from cda_client.rest import ApiException


class TestCatalogApi(unittest.TestCase):
    """CatalogApi unit test stubs"""

    def setUp(self):
        self.api = CatalogApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_cwms_data_catalog_with_dataset(self):
        """Test case for get_cwms_data_catalog_with_dataset

        Get cwmsData catalog with dataset  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
