# coding: utf-8

"""
    CWMS Data API

    CWMS REST API for Data Retrieval  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import cda_client
from cda_client.api.ratings_api import RatingsApi  # noqa: E501
from cda_client.rest import ApiException


class TestRatingsApi(unittest.TestCase):
    """RatingsApi unit test stubs"""

    def setUp(self):
        self.api = RatingsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_cwms_data_ratings_spec_with_rating_id(self):
        """Test case for delete_cwms_data_ratings_spec_with_rating_id

        Delete cwmsData ratings spec with ratingId  # noqa: E501
        """
        pass

    def test_delete_cwms_data_ratings_template_with_template_id(self):
        """Test case for delete_cwms_data_ratings_template_with_template_id

        Delete cwmsData ratings template with templateId  # noqa: E501
        """
        pass

    def test_delete_cwms_data_ratings_with_rating_id(self):
        """Test case for delete_cwms_data_ratings_with_rating_id

        Delete cwmsData ratings with ratingId  # noqa: E501
        """
        pass

    def test_get_cwms_data_ratings(self):
        """Test case for get_cwms_data_ratings

        Get cwmsData ratings  # noqa: E501
        """
        pass

    def test_get_cwms_data_ratings_metadata(self):
        """Test case for get_cwms_data_ratings_metadata

        Get cwmsData ratings metadata  # noqa: E501
        """
        pass

    def test_get_cwms_data_ratings_spec(self):
        """Test case for get_cwms_data_ratings_spec

        Get cwmsData ratings spec  # noqa: E501
        """
        pass

    def test_get_cwms_data_ratings_spec_with_rating_id(self):
        """Test case for get_cwms_data_ratings_spec_with_rating_id

        Get cwmsData ratings spec with ratingId  # noqa: E501
        """
        pass

    def test_get_cwms_data_ratings_template(self):
        """Test case for get_cwms_data_ratings_template

        Get cwmsData ratings template  # noqa: E501
        """
        pass

    def test_get_cwms_data_ratings_template_with_template_id(self):
        """Test case for get_cwms_data_ratings_template_with_template_id

        Get cwmsData ratings template with templateId  # noqa: E501
        """
        pass

    def test_get_cwms_data_ratings_with_rating_id(self):
        """Test case for get_cwms_data_ratings_with_rating_id

        Get cwmsData ratings with ratingId  # noqa: E501
        """
        pass

    def test_patch_cwms_data_ratings_with_rating_id(self):
        """Test case for patch_cwms_data_ratings_with_rating_id

        Patch cwmsData ratings with ratingId  # noqa: E501
        """
        pass

    def test_post_cwms_data_ratings(self):
        """Test case for post_cwms_data_ratings

        Post cwmsData ratings  # noqa: E501
        """
        pass

    def test_post_cwms_data_ratings_spec(self):
        """Test case for post_cwms_data_ratings_spec

        Post cwmsData ratings spec  # noqa: E501
        """
        pass

    def test_post_cwms_data_ratings_template(self):
        """Test case for post_cwms_data_ratings_template

        Post cwmsData ratings template  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
