# coding: utf-8

"""
    CWMS Data API

    CWMS REST API for Data Retrieval  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import cda_client
from cda_client.api.location_groups_api import LocationGroupsApi  # noqa: E501
from cda_client.rest import ApiException


class TestLocationGroupsApi(unittest.TestCase):
    """LocationGroupsApi unit test stubs"""

    def setUp(self):
        self.api = LocationGroupsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_cwms_data_location_group_with_group_id(self):
        """Test case for delete_cwms_data_location_group_with_group_id

        Delete cwmsData location group with groupId  # noqa: E501
        """
        pass

    def test_get_cwms_data_location_group(self):
        """Test case for get_cwms_data_location_group

        Get cwmsData location group  # noqa: E501
        """
        pass

    def test_get_cwms_data_location_group_with_group_id(self):
        """Test case for get_cwms_data_location_group_with_group_id

        Get cwmsData location group with groupId  # noqa: E501
        """
        pass

    def test_patch_cwms_data_location_group_with_group_id(self):
        """Test case for patch_cwms_data_location_group_with_group_id

        Patch cwmsData location group with groupId  # noqa: E501
        """
        pass

    def test_post_cwms_data_location_group(self):
        """Test case for post_cwms_data_location_group

        Post cwmsData location group  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
