# coding: utf-8

"""
    CWMS Data API

    CWMS REST API for Data Retrieval  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CdaError(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'message': 'str',
        'incident_identifier': 'str',
        'details': 'dict(str, object)'
    }

    attribute_map = {
        'message': 'message',
        'incident_identifier': 'incidentIdentifier',
        'details': 'details'
    }

    def __init__(self, message=None, incident_identifier=None, details=None):  # noqa: E501
        """CdaError - a model defined in Swagger"""  # noqa: E501
        self._message = None
        self._incident_identifier = None
        self._details = None
        self.discriminator = None
        if message is not None:
            self.message = message
        if incident_identifier is not None:
            self.incident_identifier = incident_identifier
        if details is not None:
            self.details = details

    @property
    def message(self):
        """Gets the message of this CdaError.  # noqa: E501


        :return: The message of this CdaError.  # noqa: E501
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this CdaError.


        :param message: The message of this CdaError.  # noqa: E501
        :type: str
        """

        self._message = message

    @property
    def incident_identifier(self):
        """Gets the incident_identifier of this CdaError.  # noqa: E501

        A randomly generated number to help identify your request in the logs for analysis..  # noqa: E501

        :return: The incident_identifier of this CdaError.  # noqa: E501
        :rtype: str
        """
        return self._incident_identifier

    @incident_identifier.setter
    def incident_identifier(self, incident_identifier):
        """Sets the incident_identifier of this CdaError.

        A randomly generated number to help identify your request in the logs for analysis..  # noqa: E501

        :param incident_identifier: The incident_identifier of this CdaError.  # noqa: E501
        :type: str
        """

        self._incident_identifier = incident_identifier

    @property
    def details(self):
        """Gets the details of this CdaError.  # noqa: E501


        :return: The details of this CdaError.  # noqa: E501
        :rtype: dict(str, object)
        """
        return self._details

    @details.setter
    def details(self, details):
        """Sets the details of this CdaError.


        :param details: The details of this CdaError.  # noqa: E501
        :type: dict(str, object)
        """

        self._details = details

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CdaError, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CdaError):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
