# coding: utf-8

"""
    CWMS Data API

    CWMS REST API for Data Retrieval  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class County(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'county_id': 'str',
        'state_initial': 'str'
    }

    attribute_map = {
        'name': 'name',
        'county_id': 'countyId',
        'state_initial': 'stateInitial'
    }

    def __init__(self, name=None, county_id=None, state_initial=None):  # noqa: E501
        """County - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._county_id = None
        self._state_initial = None
        self.discriminator = None
        if name is not None:
            self.name = name
        if county_id is not None:
            self.county_id = county_id
        if state_initial is not None:
            self.state_initial = state_initial

    @property
    def name(self):
        """Gets the name of this County.  # noqa: E501


        :return: The name of this County.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this County.


        :param name: The name of this County.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def county_id(self):
        """Gets the county_id of this County.  # noqa: E501


        :return: The county_id of this County.  # noqa: E501
        :rtype: str
        """
        return self._county_id

    @county_id.setter
    def county_id(self, county_id):
        """Sets the county_id of this County.


        :param county_id: The county_id of this County.  # noqa: E501
        :type: str
        """

        self._county_id = county_id

    @property
    def state_initial(self):
        """Gets the state_initial of this County.  # noqa: E501


        :return: The state_initial of this County.  # noqa: E501
        :rtype: str
        """
        return self._state_initial

    @state_initial.setter
    def state_initial(self, state_initial):
        """Sets the state_initial of this County.


        :param state_initial: The state_initial of this County.  # noqa: E501
        :type: str
        """

        self._state_initial = state_initial

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(County, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, County):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
