# coding: utf-8

"""
    CWMS Data API

    CWMS REST API for Data Retrieval  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Offset(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'estimate': 'bool',
        'to_datum': 'str',
        'value': 'float'
    }

    attribute_map = {
        'estimate': 'estimate',
        'to_datum': 'toDatum',
        'value': 'value'
    }

    def __init__(self, estimate=None, to_datum=None, value=None):  # noqa: E501
        """Offset - a model defined in Swagger"""  # noqa: E501
        self._estimate = None
        self._to_datum = None
        self._value = None
        self.discriminator = None
        if estimate is not None:
            self.estimate = estimate
        if to_datum is not None:
            self.to_datum = to_datum
        if value is not None:
            self.value = value

    @property
    def estimate(self):
        """Gets the estimate of this Offset.  # noqa: E501


        :return: The estimate of this Offset.  # noqa: E501
        :rtype: bool
        """
        return self._estimate

    @estimate.setter
    def estimate(self, estimate):
        """Sets the estimate of this Offset.


        :param estimate: The estimate of this Offset.  # noqa: E501
        :type: bool
        """

        self._estimate = estimate

    @property
    def to_datum(self):
        """Gets the to_datum of this Offset.  # noqa: E501


        :return: The to_datum of this Offset.  # noqa: E501
        :rtype: str
        """
        return self._to_datum

    @to_datum.setter
    def to_datum(self, to_datum):
        """Sets the to_datum of this Offset.


        :param to_datum: The to_datum of this Offset.  # noqa: E501
        :type: str
        """

        self._to_datum = to_datum

    @property
    def value(self):
        """Gets the value of this Offset.  # noqa: E501


        :return: The value of this Offset.  # noqa: E501
        :rtype: float
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this Offset.


        :param value: The value of this Offset.  # noqa: E501
        :type: float
        """

        self._value = value

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Offset, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Offset):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
