# coding: utf-8

"""
    CWMS Data API

    CWMS REST API for Data Retrieval  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from cda_client.models.abstract_rating_metadata import AbstractRatingMetadata  # noqa: F401,E501

class TransitionalRating(AbstractRatingMetadata):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'source_ratings': 'list[str]',
        'conditions': 'list[str]',
        'evaluations': 'list[str]'
    }
    if hasattr(AbstractRatingMetadata, "swagger_types"):
        swagger_types.update(AbstractRatingMetadata.swagger_types)

    attribute_map = {
        'source_ratings': 'source-ratings',
        'conditions': 'conditions',
        'evaluations': 'evaluations'
    }
    if hasattr(AbstractRatingMetadata, "attribute_map"):
        attribute_map.update(AbstractRatingMetadata.attribute_map)

    def __init__(self, source_ratings=None, conditions=None, evaluations=None, *args, **kwargs):  # noqa: E501
        """TransitionalRating - a model defined in Swagger"""  # noqa: E501
        self._source_ratings = None
        self._conditions = None
        self._evaluations = None
        self.discriminator = None
        if source_ratings is not None:
            self.source_ratings = source_ratings
        if conditions is not None:
            self.conditions = conditions
        if evaluations is not None:
            self.evaluations = evaluations
        AbstractRatingMetadata.__init__(self, *args, **kwargs)

    @property
    def source_ratings(self):
        """Gets the source_ratings of this TransitionalRating.  # noqa: E501


        :return: The source_ratings of this TransitionalRating.  # noqa: E501
        :rtype: list[str]
        """
        return self._source_ratings

    @source_ratings.setter
    def source_ratings(self, source_ratings):
        """Sets the source_ratings of this TransitionalRating.


        :param source_ratings: The source_ratings of this TransitionalRating.  # noqa: E501
        :type: list[str]
        """

        self._source_ratings = source_ratings

    @property
    def conditions(self):
        """Gets the conditions of this TransitionalRating.  # noqa: E501


        :return: The conditions of this TransitionalRating.  # noqa: E501
        :rtype: list[str]
        """
        return self._conditions

    @conditions.setter
    def conditions(self, conditions):
        """Sets the conditions of this TransitionalRating.


        :param conditions: The conditions of this TransitionalRating.  # noqa: E501
        :type: list[str]
        """

        self._conditions = conditions

    @property
    def evaluations(self):
        """Gets the evaluations of this TransitionalRating.  # noqa: E501


        :return: The evaluations of this TransitionalRating.  # noqa: E501
        :rtype: list[str]
        """
        return self._evaluations

    @evaluations.setter
    def evaluations(self, evaluations):
        """Sets the evaluations of this TransitionalRating.


        :param evaluations: The evaluations of this TransitionalRating.  # noqa: E501
        :type: list[str]
        """

        self._evaluations = evaluations

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TransitionalRating, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TransitionalRating):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
